# [作業目標]

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

# 作業 

### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```


In [6]:
a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)

type(a):  <class 'numpy.ndarray'>
a.dtype:  int32


一個是看類別(int,string)，一個是看元素型態(元素、位數)


### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [14]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.18.5


In [26]:
def is_dtype(a, t):
    return a.dtype is np.dtype(t)

In [28]:
a = np.random.randint(10, size=6) 
print(a)

print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True


[2 0 2 7 9 3]
True
True
True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

type() 是檢查變數的型態，而不是元素的型態； is 相對 == 更嚴格，一定要型態正確才會回傳 True。
